### ISSUE TITLE
typo: codeCount -> nodeCount

### ISSUE THREAD

**Issue by dudebing99** [delida/MOACDocs-CHN#1]
https://moacdocs-chn.readthedocs.io/zh_CN/latest/appchain/%E5%BA%94%E7%94%A8%E9%93%BE%E8%8A%82%E7%82%B9%E7%9A%84%E6%9B%B4%E6%9B%BF.html

**Comment by delida** [comment]
> https://moacdocs-chn.readthedocs.io/zh_CN/latest/appchain/%E5%BA%94%E7%94%A8%E9%93%BE%E8%8A%82%E7%82%B9%E7%9A%84%E6%9B%B4%E6%9B%BF.html

fixed, thanks!
